/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reserva;

/**
 *
 * @author DavAtem
 */
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlab_cliente = new javax.swing.JLabel();
        jtxt_cedula = new javax.swing.JTextField();
        jlab_nombre = new javax.swing.JLabel();
        jtxt_nombre = new javax.swing.JTextField();
        jtxt_telefono = new javax.swing.JTextField();
        jtxt_direccion = new javax.swing.JTextField();
        jlab_telefono = new javax.swing.JLabel();
        jlab_cedula = new javax.swing.JLabel();
        jlab_direccion = new javax.swing.JLabel();
        jbtn_guardarcli = new javax.swing.JButton();
        jbtn_regresarcli = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlab_cliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlab_cliente.setText("Registrar Cliente");

        jlab_nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlab_nombre.setText("Nombre");

        jlab_telefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlab_telefono.setText("Telefono");

        jlab_cedula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlab_cedula.setText("Cedula");

        jlab_direccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlab_direccion.setText("Direccion");

        jbtn_guardarcli.setBackground(new java.awt.Color(102, 255, 102));
        jbtn_guardarcli.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jbtn_guardarcli.setText("Guardar");
        jbtn_guardarcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_guardarcliActionPerformed(evt);
            }
        });

        jbtn_regresarcli.setBackground(new java.awt.Color(204, 102, 0));
        jbtn_regresarcli.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jbtn_regresarcli.setText("Regresar");
        jbtn_regresarcli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_regresarcliMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(jlab_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlab_nombre)
                    .addComponent(jlab_cedula)
                    .addComponent(jlab_telefono)
                    .addComponent(jlab_direccion))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn_guardarcli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(jbtn_regresarcli))
                    .addComponent(jtxt_cedula)
                    .addComponent(jtxt_nombre)
                    .addComponent(jtxt_telefono)
                    .addComponent(jtxt_direccion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jlab_cliente)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlab_cedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlab_nombre))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlab_telefono)
                    .addComponent(jtxt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlab_direccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_regresarcli)
                    .addComponent(jbtn_guardarcli))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_regresarcliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_regresarcliMouseClicked
Inicio inicio = new Inicio();
inicio.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jbtn_regresarcliMouseClicked

    private void jbtn_guardarcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_guardarcliActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("org.mariadb.jdbc.Driver");
            System.out.println("Driver esta cargando correctamente");
            Connection con=null;
            con=DriverManager.getConnection("jdbc:mysql://192.168.130.130/proyecto1reserva","alumno","remoto");
            System.out.println("Base de datos conectada");
            Statement stmt=con.createStatement();
            stmt.executeUpdate("INSERT INTO cliente VALUES('"+jtxt_cedula.getText()+"','"+jtxt_nombre.getText()+"','"+jtxt_telefono.getText()+"','"+jtxt_direccion.getText()+"')");
            System.out.println("Registrado correctamente");
        } catch (ClassNotFoundException ex) {
            System.out.println(ex.getException());
        }
        catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
        JOptionPane.showMessageDialog(null,"El alumno se a registrado correctamente");
    
    }//GEN-LAST:event_jbtn_guardarcliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn_guardarcli;
    private javax.swing.JButton jbtn_regresarcli;
    private javax.swing.JLabel jlab_cedula;
    private javax.swing.JLabel jlab_cliente;
    private javax.swing.JLabel jlab_direccion;
    private javax.swing.JLabel jlab_nombre;
    private javax.swing.JLabel jlab_telefono;
    private javax.swing.JTextField jtxt_cedula;
    private javax.swing.JTextField jtxt_direccion;
    private javax.swing.JTextField jtxt_nombre;
    private javax.swing.JTextField jtxt_telefono;
    // End of variables declaration//GEN-END:variables
}
