/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reserva;

/**
 *
 * @author DavAtem
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlab_titulo = new javax.swing.JLabel();
        jbtn_cliente = new javax.swing.JButton();
        jbtn_mesa = new javax.swing.JButton();
        jbtn_reserva = new javax.swing.JButton();
        jbtn_menu = new javax.swing.JButton();
        jbtn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jlab_titulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jlab_titulo.setText("RESTAURANT");

        jbtn_cliente.setBackground(new java.awt.Color(102, 255, 102));
        jbtn_cliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtn_cliente.setText("Cliente");
        jbtn_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_clienteMouseClicked(evt);
            }
        });

        jbtn_mesa.setBackground(new java.awt.Color(102, 255, 102));
        jbtn_mesa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtn_mesa.setText("Mesa");
        jbtn_mesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_mesaMouseClicked(evt);
            }
        });

        jbtn_reserva.setBackground(new java.awt.Color(102, 255, 102));
        jbtn_reserva.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtn_reserva.setText("Reserva");
        jbtn_reserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_reservaMouseClicked(evt);
            }
        });

        jbtn_menu.setBackground(new java.awt.Color(102, 255, 102));
        jbtn_menu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtn_menu.setText("Menu");
        jbtn_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_menuMouseClicked(evt);
            }
        });

        jbtn_salir.setBackground(new java.awt.Color(204, 102, 0));
        jbtn_salir.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jbtn_salir.setText("Salir");
        jbtn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_salirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtn_reserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_menu)
                    .addComponent(jbtn_mesa))
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlab_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtn_salir)
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jlab_titulo)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_cliente)
                    .addComponent(jbtn_mesa))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_reserva)
                    .addComponent(jbtn_menu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jbtn_salir)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_clienteMouseClicked
Cliente cliente = new Cliente();
cliente.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jbtn_clienteMouseClicked

    private void jbtn_mesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_mesaMouseClicked
Mesa mesa = new Mesa();
mesa.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jbtn_mesaMouseClicked

    private void jbtn_reservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_reservaMouseClicked
Reserva reserva = new Reserva();
reserva.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jbtn_reservaMouseClicked

    private void jbtn_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_menuMouseClicked
Menu menu = new Menu();
menu.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jbtn_menuMouseClicked

    private void jbtn_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_salirMouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_salirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn_cliente;
    private javax.swing.JButton jbtn_menu;
    private javax.swing.JButton jbtn_mesa;
    private javax.swing.JButton jbtn_reserva;
    private javax.swing.JButton jbtn_salir;
    private javax.swing.JLabel jlab_titulo;
    // End of variables declaration//GEN-END:variables
}
