/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reserva;

/**
 *
 * @author DavAtem
 */
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlab_menu = new javax.swing.JLabel();
        jlab_nombre_menu = new javax.swing.JLabel();
        jlab_descripcion = new javax.swing.JLabel();
        jlab_precio = new javax.swing.JLabel();
        jtxt_nombre_menu = new javax.swing.JTextField();
        jtxt_descripcion = new javax.swing.JTextField();
        jtxt_precio = new javax.swing.JTextField();
        jbtn_guardarmen = new javax.swing.JButton();
        jbtn_regresarmen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlab_menu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlab_menu.setText("Registrar Menu");

        jlab_nombre_menu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlab_nombre_menu.setText("Nombre del Menu");

        jlab_descripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlab_descripcion.setText("Descripcion");

        jlab_precio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlab_precio.setText("Precio");

        jbtn_guardarmen.setBackground(new java.awt.Color(102, 255, 102));
        jbtn_guardarmen.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jbtn_guardarmen.setText("Guardar");
        jbtn_guardarmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_guardarmenActionPerformed(evt);
            }
        });

        jbtn_regresarmen.setBackground(new java.awt.Color(204, 102, 0));
        jbtn_regresarmen.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jbtn_regresarmen.setText("Regresar");
        jbtn_regresarmen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_regresarmenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jlab_menu))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlab_nombre_menu)
                            .addComponent(jlab_descripcion)
                            .addComponent(jlab_precio))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn_guardarmen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addComponent(jbtn_regresarmen))
                            .addComponent(jtxt_nombre_menu, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxt_descripcion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxt_precio))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jlab_menu)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_nombre_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlab_nombre_menu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlab_descripcion))
                .addGap(18, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlab_precio))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_guardarmen)
                    .addComponent(jbtn_regresarmen))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_regresarmenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_regresarmenMouseClicked
Inicio inicio = new Inicio();
inicio.setVisible(true);
this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_regresarmenMouseClicked

    private void jbtn_guardarmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_guardarmenActionPerformed
        try {
            Class.forName("org.mariadb.jdbc.Driver");
            System.out.println("Driver esta cargando correctamente");
            Connection con=null;
            con=DriverManager.getConnection("jdbc:mysql://192.168.130.130/proyecto1reserva","alumno","remoto");
            System.out.println("Base de datos conectada");
            Statement stmt=con.createStatement();
            stmt.executeUpdate("INSERT INTO menu VALUES('"+jtxt_nombre_menu.getText()+"','"+jtxt_descripcion.getText()+"','"+jtxt_precio.getText()+"')");
            System.out.println("Registrado correctamente");
        } catch (ClassNotFoundException ex) {
            System.out.println(ex.getException());
        }
        catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
        JOptionPane.showMessageDialog(null,"El alumno se a registrado correctamente");
    }//GEN-LAST:event_jbtn_guardarmenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn_guardarmen;
    private javax.swing.JButton jbtn_regresarmen;
    private javax.swing.JLabel jlab_descripcion;
    private javax.swing.JLabel jlab_menu;
    private javax.swing.JLabel jlab_nombre_menu;
    private javax.swing.JLabel jlab_precio;
    private javax.swing.JTextField jtxt_descripcion;
    private javax.swing.JTextField jtxt_nombre_menu;
    private javax.swing.JTextField jtxt_precio;
    // End of variables declaration//GEN-END:variables
}
