/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reserva;

/**
 *
 * @author DavAtem
 */
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class Mesa extends javax.swing.JFrame {

    /**
     * Creates new form Mesa
     */
    public Mesa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlab_mesa = new javax.swing.JLabel();
        jlab_cantpersonas = new javax.swing.JLabel();
        jlab_ubicacion = new javax.swing.JLabel();
        jtxt_cantpersonas = new javax.swing.JTextField();
        jtxt_ubicacion = new javax.swing.JTextField();
        jbtn_guardarmes = new javax.swing.JButton();
        jbnt_regresarmes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlab_mesa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlab_mesa.setText("Registrar Mesa");

        jlab_cantpersonas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlab_cantpersonas.setText("Cantidad de personas");

        jlab_ubicacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlab_ubicacion.setText("Ubicacion");

        jtxt_ubicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_ubicacionActionPerformed(evt);
            }
        });

        jbtn_guardarmes.setBackground(new java.awt.Color(102, 255, 102));
        jbtn_guardarmes.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jbtn_guardarmes.setText("Guardar");
        jbtn_guardarmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_guardarmesActionPerformed(evt);
            }
        });

        jbnt_regresarmes.setBackground(new java.awt.Color(204, 102, 0));
        jbnt_regresarmes.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jbnt_regresarmes.setText("Regresar");
        jbnt_regresarmes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbnt_regresarmesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlab_cantpersonas)
                    .addComponent(jlab_ubicacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlab_mesa)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtxt_cantpersonas)
                        .addComponent(jtxt_ubicacion)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbtn_guardarmes)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                            .addComponent(jbnt_regresarmes))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jlab_mesa)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_cantpersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlab_cantpersonas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlab_ubicacion))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnt_regresarmes)
                    .addComponent(jbtn_guardarmes))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_ubicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_ubicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_ubicacionActionPerformed

    private void jbnt_regresarmesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbnt_regresarmesMouseClicked
Inicio inicio = new Inicio();
inicio.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jbnt_regresarmesMouseClicked

    private void jbtn_guardarmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_guardarmesActionPerformed
        try {
            Class.forName("org.mariadb.jdbc.Driver");
            System.out.println("Driver esta cargando correctamente");
            Connection con=null;
            con=DriverManager.getConnection("jdbc:mysql://192.168.130.130/proyecto1reserva","alumno","remoto");
            System.out.println("Base de datos conectada");
            Statement stmt=con.createStatement();
            stmt.executeUpdate("INSERT INTO mesa VALUES('"+jtxt_cantpersonas.getText()+"','"+jtxt_ubicacion.getText()+"')");
            System.out.println("Registrado correctamente");
        } catch (ClassNotFoundException ex) {
            System.out.println(ex.getException());
        }
        catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
        JOptionPane.showMessageDialog(null,"El alumno se a registrado correctamente");
    }//GEN-LAST:event_jbtn_guardarmesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbnt_regresarmes;
    private javax.swing.JButton jbtn_guardarmes;
    private javax.swing.JLabel jlab_cantpersonas;
    private javax.swing.JLabel jlab_mesa;
    private javax.swing.JLabel jlab_ubicacion;
    private javax.swing.JTextField jtxt_cantpersonas;
    private javax.swing.JTextField jtxt_ubicacion;
    // End of variables declaration//GEN-END:variables
}
